name: CI/CD - Build e Publicação no Docker Hub e AWS

on:
  push:
    branches: [ "chore/configure-docker" ] 
  workflow_dispatch: 

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    needs: build_and_test
    if: github.ref == 'refs/heads/chore/configure-docker'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Login docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Construir e Publicar a imagem
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
